name: UI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run tests (Allure results)
        run: |
          pytest -m regression --alluredir=allure-results

      - name: Check allure results
        run: |
          ls -la allure-results || echo "NO RESULTS"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Allure
        run: |
          npm install -g allure-commandline --save-dev

      - name: Copy history
        run: |
          mkdir -p allure-results/history
          cp -r gh-pages/history/* allure-results/history || true

      - name: Debug report
        run: |
          ls -la
          ls -la allure-report

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Load previous report history
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report