name: UI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run tests (Allure results)
        run: |
          pytest -m regression --alluredir=allure-results

      - name: Check allure results
        run: |
          ls -la allure-results || echo "NO RESULTS"

      # Устанавливаем Allure CLI
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Генерируем HTML отчёт
      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      # Проверка (очень важно)
      - name: Debug report
        run: |
          ls -la
          ls -la allure-report

      # Деплой
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report